### ISSUE TITLE
IOS. Вывести свое место расположение на карте

### ISSUE THREAD

**Issue by hastlerr** [Reedlee/poor-cop#11]
## Что нужно сделать
1. Получить разрешение на использование геопозиции телефона
2. Вскормить полученные данные карте что бы она отобразила текущее место расположение на карте

## Как это сделать
1. Получить разрешение на использование геопозиции телефона
запросить разрежение в info.list

2. Вскормить полученные данные карте 
Полученные данные вскормить нужному методу карты что бы та в свою очередь показала локацию телефона

## Зачем это нужно

Нужно, чтобы IOS приложение умело отправлять координаты точки в ROR приложение и обрабатывать полученные данные.

## Критерии готовности
Флажок на карте с точным место расположением телефона

**Comment by samatbek** [comment]
Закрыл этот тикет потому что, он дублируется с #22 IOS Получение текущего месторасположения, который уже закрыт.
