### ISSUE TITLE
 Android. Найти библиотеку для работы с картой

### ISSUE THREAD

**Issue by Reedlee** [Reedlee/poor-cop#24]
# Android
## Что нужно сделать
Нужно найти библиотеку, которая позволит работать с картой.

## Как это сделать
     google поиск выдал 2 библиотеки:
1. 
2. osmdroid
Остановился на osmdroid

## Зачем это нужно
Это библиотека нужна, чтобы в дальнейшем отображать точки(координаты) на карте.

## Критерии готовности
 Для работы с картами выбрана библиотека osmdroid 
```Gherkin

```

**Comment by neildvr** [comment]
C @mkylychev приняли окончательное решение использовать библиотеку OSMdroid
