### ISSUE TITLE
Android. API интерактор(отправка и получение)

### ISSUE THREAD

**Issue by Reedlee** [Reedlee/poor-cop#25]
# Android
## Что нужно сделать
Написать методы которые будут отправлять точку на сервер и получать точки с сервера
## Как это сделать
Воспользоваться готовой библиотекой для работы с REST API - Retrofit
реализовать get и post запросы с помощью этой библиотеки
## Зачем это нужно
Нужно, чтобы моб приложение умело отправлять координаты точки в ROR приложение и обрабатывать полученные данные.
 
## Критерии готовности
```Готово.

```

**Comment by mkylychev** [comment]
Сделано
