### ISSUE TITLE
Android. Получение доступа к gps телефона

### ISSUE THREAD

**Issue by Reedlee** [Reedlee/poor-cop#27]
# Android
## Что нужно сделать
       Нужно получить доступ к gps телефона
## Как это сделать
      нужно в файле AndroidManifest.xml добавить следующие строки -
      <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
 
## Зачем это нужно
     Доступ к gps нужен для того, что бы определять местоположение пользователя

## Критерии готовности
     готово, но возможны некоторые сложности с Permisions на анроид с версий 6 и выше
```Gherkin

```

**Comment by mkylychev** [comment]
Cделано!
